# Ubuntu 14.04 Trusty support
sudo: true

dist: trusty

language: cpp

compiler:
  - gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      
script:
  - sudo ./configure.sh

notifications:
  slack: vss-sdk:UbGYb9E8B9Tkh4dHXwrdliTc
